2023-03-18 14:30:39,370 - tools - ERROR - 57 - 14760 - 17248: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_bpnn.py", line 96, in predict_without_history_power
    result = self.__model_bpnn_withoutp.predict(feature)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 1591, in predict
    y_pred = self._forward_pass_fast(X)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 160, in _forward_pass_fast
    X = self._validate_data(X, accept_sparse=["csr", "csc"], reset=False)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\sklearn\base.py", line 600, in _validate_data
    self._check_n_features(X, reset=reset)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\sklearn\base.py", line 400, in _check_n_features
    raise ValueError(
ValueError: X has 6 features, but MLPRegressor is expecting 5 features as input.
2023-03-18 14:30:39,374 - tools - ERROR - 57 - 14760 - 17248: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:39,375 - ensemble_learning - ERROR - 1535 - 14760 - 17248: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:40,387 - tools - ERROR - 57 - 21524 - 11152: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:40,389 - tools - ERROR - 57 - 21524 - 11152: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:40,390 - ensemble_learning - ERROR - 1535 - 21524 - 11152: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:41,403 - tools - ERROR - 57 - 4204 - 1744: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:41,405 - tools - ERROR - 57 - 4204 - 1744: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:41,406 - ensemble_learning - ERROR - 1535 - 4204 - 1744: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:42,410 - tools - ERROR - 57 - 22376 - 2936: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:42,412 - tools - ERROR - 57 - 22376 - 2936: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:42,413 - ensemble_learning - ERROR - 1535 - 22376 - 2936: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:43,414 - tools - ERROR - 57 - 2332 - 18120: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:43,416 - tools - ERROR - 57 - 2332 - 18120: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:43,417 - ensemble_learning - ERROR - 1535 - 2332 - 18120: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:44,419 - tools - ERROR - 57 - 15252 - 22808: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:44,421 - tools - ERROR - 57 - 15252 - 22808: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:44,422 - ensemble_learning - ERROR - 1535 - 15252 - 22808: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:45,432 - tools - ERROR - 57 - 23004 - 16128: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:45,434 - tools - ERROR - 57 - 23004 - 16128: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:45,435 - ensemble_learning - ERROR - 1535 - 23004 - 16128: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:46,436 - tools - ERROR - 57 - 14048 - 15276: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:46,438 - tools - ERROR - 57 - 14048 - 15276: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:46,439 - ensemble_learning - ERROR - 1535 - 14048 - 15276: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:47,441 - tools - ERROR - 57 - 11392 - 18748: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:47,443 - tools - ERROR - 57 - 11392 - 18748: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:47,444 - ensemble_learning - ERROR - 1535 - 11392 - 18748: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:48,365 - tools - ERROR - 57 - 3964 - 11960: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:48,367 - tools - ERROR - 57 - 3964 - 11960: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:48,368 - ensemble_learning - ERROR - 1535 - 3964 - 11960: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:49,370 - tools - ERROR - 57 - 14832 - 7616: predict_short_power error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 214, in predict_short_power
    predict_result_raw = fitted_model(feature=test_feature, history_power=None,
  File "F:\Kuafu_20230308\model\_mffs.py", line 99, in predict_without_history_power
    input_test[i, :] = (input_test[i, :] - mi) / (ma - mi)
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
2023-03-18 14:30:49,372 - tools - ERROR - 57 - 14832 - 7616: ensemble_learning_evaluate_short error: 
Traceback (most recent call last):
  File "F:\Kuafu_20230308\common\tools.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "F:\Kuafu_20230308\app\ensemble_learning\ensemble_learning.py", line 50, in ensemble_learning_evaluate_short
    predict_result_cluster, time_predict_cluster = predict_short_power(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:30:49,372 - ensemble_learning - ERROR - 1535 - 14832 - 7616: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\ensemble_learning.py", line 1489, in ensemble_learning_evaluate_short
    time_predict_cluster, result, model_state = ensemble_learning.ensemble_learning_evaluate_short(
TypeError: cannot unpack non-iterable NoneType object
2023-03-18 14:31:15,106 - model_evaluation - ERROR - 183 - 14092 - 20924: single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\model_evaluation.py", line 158, in evaluate_for_station
    (predict_power.loc[:, 'forecast_time'].iloc[0], predict_power.loc[:, 'forecast_time'].iloc[-1]))
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2023-03-18 14:31:15,148 - model_evaluation - ERROR - 183 - 14092 - 20924: single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\model_evaluation.py", line 158, in evaluate_for_station
    (predict_power.loc[:, 'forecast_time'].iloc[0], predict_power.loc[:, 'forecast_time'].iloc[-1]))
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2023-03-18 14:31:21,280 - model_evaluation - ERROR - 183 - 14092 - 20924: single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\model_evaluation.py", line 158, in evaluate_for_station
    (predict_power.loc[:, 'forecast_time'].iloc[0], predict_power.loc[:, 'forecast_time'].iloc[-1]))
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
2023-03-18 14:31:21,337 - model_evaluation - ERROR - 183 - 14092 - 20924: single positional indexer is out-of-bounds
Traceback (most recent call last):
  File "F:\Kuafu_20230308\task\mysql\model_evaluation.py", line 158, in evaluate_for_station
    (predict_power.loc[:, 'forecast_time'].iloc[0], predict_power.loc[:, 'forecast_time'].iloc[-1]))
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1520, in _getitem_axis
    self._validate_integer(key, axis)
  File "D:\Users\67436\anaconda3\envs\kuafupy38\lib\site-packages\pandas\core\indexing.py", line 1452, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
